accounts/urls.py
from django.urls import path, re_path

from .views import (
    account_home,
    account_change_profile,
    change_password,
    remove_from_basket
)


urlpatterns = [
    path('edit/', account_change_profile, name='account_change_profile'),
    path('change_password/', change_password, name='change_password'),
    re_path('^(?P<id>\d+)/$', account_home, name='account'),
    re_path('^(?P<id_element>\d+)/remove$', remove_from_basket, name='remove_from_basket'),
]

post/urls.py
from django.urls import path, re_path
from .views import (
    home_page,
    detail_page,
    edit_page,
    delete_page,
    create_post,
    like_page,
    high_middle_low_rate,
    dynamic_image,
    category_view,
    category_detail_view,
    add_comment,
    display_posts_by_category,
    add_to_favorite,
    search,
    add_to_basket,
    )

app_name = 'post-api'

urlpatterns = [
    path('', home_page, name='home_page'),
    path('add_comment/', add_comment, name='add_comment'),
    path('search/', search, name='search'),
    path('display_posts_by_category', display_posts_by_category, name='display_posts_by_category'),
    re_path('^rate/(?P<slug>[-\w]+)/$', high_middle_low_rate, name='high_middle_low_rate'),
    path('category/', category_view, name='category_view'),
    re_path('^category/(?P<slug>[-\w]+)/$', category_detail_view, name='category_detail_view'),
    path('create/', create_post, name='create_post'),
    path('show_post_image/', dynamic_image, name='dynamic_image'),
    re_path('^(?P<id>\d+)/$', detail_page, name='detail_page'),
    re_path('^(?P<id>\d+)/add_to_basket$', add_to_basket, name='add_to_basket'),
    re_path('^(?P<id>\d+)/add_to_favorite/$', add_to_favorite, name='add_to_favorite'),
    re_path('^(?P<id>\d+)/like$', like_page, name='like_page'),
    re_path('^(?P<id>\d+)/edit/$', edit_page, name='edit_page'),
    re_path('^(?P<id>\d+)/delete/$', delete_page, name='delete_page'),
]

project2big/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

from accounts.views import login_view, logout_view, register_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('start.urls', 'start'), namespace='start')),
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('register/', register_view, name='register_view'),
    path('posts/', include(('post.urls', 'post'), namespace='post')),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('chat/', include(('chat_message.urls', 'chat_message'), namespace='chat_message')),
    path('api-auth/', include('rest_framework.urls')),

    path('api/posts/', include('post.post_api.urls')),
    path('api/account/', include('accounts.api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

start/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

post/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import F
from django.db import models

import math


from rest_framework.reverse import reverse as api_reverse
from accounts.models import UserProfile
from comments.models import Comments
from likes.models import Like


def content_type_queryset(model, content_type, id):
    return model.objects.filter(content_type=content_type, object_id=id).order_by("-timestamp")


class PostManager(models.Manager):
    def home(self):
        res = []
        posts = self.select_related("category", "user").all().order_by('-timestamp')
        for p in posts:
            if len(res) == 0:
                res.append(p)

            if res[-1].category != p.category:
                res.append(p)

        return res

    def high_rate(self, *args, **kwargs):
        return self.filter(rate__range=(25, 101))

    def middle_rate(self, *args, **kwargs):
        return self.filter(rate__range=(10, 25))

    def low_rate(self, *args, **kwargs):
        return self.filter(rate__range=(0, 10))


def generate_image_path(instance, filename):
    filename = instance.id
    return "{directory}/{file}".format(directory=instance.id//7, file=filename)


# def upload_location(instance, filename):
#     PostModel = instance.__class__
#     new_id = PostModel.objects.order_by("id").last().id + 1
#     return "%s/%s" % (new_id, filename)


class Category(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField()
    image = models.ImageField(upload_to='media',
                              null=True,
                              blank=True,
                              )

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_category_url(self):
        return reverse("post:category_detail_view", kwargs={"slug": self.name})

    def __str__(self):
        return self.name


class Posts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()

    image = models.ImageField(upload_to='media',
                              null=True,
                              blank=True,
                              )

    # height_field = models.IntegerField(default=0)
    # width_field = models.IntegerField(default=0)

    rate = models.PositiveSmallIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    objects = PostManager()

    likes = GenericRelation(Like)

    class Meta:
        verbose_name = 'Posts'
        verbose_name_plural = 'Post'

    def get_user_url(self):
        return reverse("accounts:account", kwargs={"id": self.user_id})

    def get_absolute_url(self):
        return reverse("post:detail_page", kwargs={"id": self.id})

    def edit_post(self):
        return reverse("post:edit_page", kwargs={"id": self.id})

    def delete_post(self):
        return reverse("post:delete_page", kwargs={"id": self.id})

    def update_view(self, id):
        self.rate = math.ceil(self.total_likes / (self.views + 1))
        self.views = F('views') + 1
        self.save(update_fields=('views',))
        post = Posts.objects.get(id=id)
        return post

    @property
    def total_likes(self):
        return self.likes.count()

    def is_like(self, user):
        if not user.is_authenticated:
            return False
        obj_type = ContentType.objects.get_for_model(self)
        likes = Like.objects.filter(content_type=obj_type, object_id=self.id, user=user)
        return likes.exists()

    def is_favorite(self, user):
        if not user.is_authenticated:
            return False
        userprofile = UserProfile.objects.get(user=user)
        return self in userprofile.favorite_posts.all()

    def get_api_url(self, request=None):
        return api_reverse("post-api:detail", kwargs={"pk": self.pk}, request=request)

    def __str__(self):
        return self.title


# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug(instance)
#
#     if instance.content:
#         html_string = instance.get_markdown()
#         read_time_var = get_read_time(html_string)
#         instance.read_time = read_time_var
#
#
# pre_save.connect(pre_save_post_receiver, sender=Post)

templates/home/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en" class="full-height">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/compiled.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static "css/custom_style.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    {% block head %}
    {% endblock %}

</head>
<body class="user_div">

<nav class="navbar navbar-expand-lg navbar-dark primary-color fixed-top scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url "start:home" %}">
        <strong>Python for everyone</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "post:home_page" %}">Posts
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url "post:search" %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
          <ul class="navbar-nav nav-flex-icons">
              {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">You: {{ request.user.username }}</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url "accounts:account" id=request.user.id %}">My account</a>
                        <a class="dropdown-item" href="{% url "accounts:account_change_profile" %}">Edit account</a>
                        <a class="dropdown-item" href="{% url "accounts:change_password" %}">Change password</a>
                        <form action="{% url "logout_view" %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="dropdown-item" value="Logout">
                        </form>
                    </div>
                  </li>
              {% else %}
                  <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url "login_view" %}">Login</a>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url "register_view" %}">Register</a>
                      </li>
                    </ul>
              {% endif %}
          </ul>

      </div>
    </div>
  </nav>

<div class="user_div">
    <br><br>
    {% block content %}

    {% endblock %}
    <br>
</div>


    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/compiled.min.js" %}"></script>
</body>
</html>

templates/home/delete_page.html
{% extends "home/base.html" %}


{% block content %}
    <br><br>
    <div class="container">
        <div class="col-xs-8 col-xs-offset-2">
            <form action="." method="POST">
                {% csrf_token %}
                <h2>Are you sure that you want to delete {{ post.title }}</h2>
                <input type='submit' class='btn btn-default' value='Delete'>
                <a class="btn btn-warning" href="{% url "post:home_page" %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/home/detail_page.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="user_div">
    <div class="container">

    <section class="text-center my-5">
      <div class="row">
        <div class="col-12">
          <div class="img-back overlay z-depth-2 mb-4 text-center" >
            <img class="img-fluid imgdetail" src="{{ post.image.url }}" alt="Sample image">
          </div>
    {#      <a href="#!" class="pink-text"><h6 class="font-weight-bold mb-3"><i class="fa fa-map pr-2"></i>Adventure</h6></a>#}
          <h4 class="font-weight-bold mb-3"><strong>{{ post.title }}</strong></h4>
          <h5>by <a class="font-weight-bold" href="{{ post.get_user_url }}">{{ post.user.username }}</a>, {{ post.timestamp|timesince }} ago</h5>
          <h5>Article rate: {{ post.rate }} | Views: {{ post.views }}</h5>
          <h6>Category: {{ post.category.name }}</h6>
          <hr>
            <h3 class="dark-grey-text">{{ post.content }}</h3>
            <hr>
            <h4 data-id="{{ post.total_likes }}" id="total_likes">Total likes: {{ post.total_likes }}</h4>
            {% if user.is_authenticated %}
                {% if not check_like %}
                    <a href="{% url "post:like_page" id=post.id%}" class="btn btn-primary like_class" id="like_dislike" data-id="{{ post.id }}">Like</a>
                {% else %}
                    <a href="{% url "post:like_page" id=post.id%}" class="btn btn-warning like_class" id="like_dislike" data-id="{{ post.id }}">Remove like</a>
                {% endif %}

                {% if not check_favorite %}
                    <a class="btn btn-success" id="favorite_add_remove" href="{% url "post:add_to_favorite" id=post.id  %}" data-id="{{ post.id }}">Add to favorite</a>
                {% else %}
                    <a class="btn btn-warning" id="favorite_add_remove" href="{% url "post:add_to_favorite" id=post.id  %}" data-id="{{ post.id }}">Remove from favorite</a>
                {% endif %}
                <div id="BasketDiv">
                {% if basket == 'False' %}
                    <a href="{% url "post:add_to_basket" id=post.id %}" data-action="Add" id="Basketid" data-id="{{ post.id }}" class="btn btn-success basket_new">Add to basket</a>
                {% else %}
                    <a href="{% url "post:add_to_basket" id=post.id %}" data-action="Remove" id="Basketid" data-id="{{ post.id }}" class="btn btn-warning basket_new">Remove from basket</a>
                {% endif %}
                </div>
            {% endif %}
            <br>
            {% if request.user == post.user %}
                <hr>
                <a href="{{ post.edit_post }}" class="btn btn-success">Edit post</a>
                <a href="{{ post.delete_post }}" class="btn btn-danger">Delete post</a>
            {% endif %}
        </div>
      </div>
        <hr>
    </section>
    {% if request.user.is_authenticated %}
        <form action="." method="POST">
            <input type="hidden" id="post" data-id="{{ post.id }}">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" id="add_comment" data-toggle="modal" data-target="#myModal">
        </form>
    {% else %}
        <h2>If you want to add new comments, you must be register</h2>
    {% endif %}
    <hr>
    <h2>All comments:</h2>
    <br>
    <br>
    <div class="new_comment">

    </div>
    <br>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            Comment successfully created
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    {% if comments %}
        {% for comment in comments %}
              <div class="row">
                <div class="col-md-12">
                  <div class="mdb-feed">
                    <div class="news">
                      <div class="label">
                        {% if comment.userprofile.image %}
                            <img src="{{ comment.userprofile.image.url }}" class="rounded-circle z-depth-1-half">
                        {% endif %}
                      </div>
                      <div class="excerpt">
                        <div class="brief">
                          <a class="name" href="{{ comment.get_user_url }}">{{ comment.user.username }}</a>
                          <div class="date">{{ comment.timestamp|timesince }} ago</div>
                        </div>
                        <div class="added-text">{{ comment.content }}</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <br>
        {% endfor %}

    {% else %}
        <br>
        <h2 class="alert alert-info">Ops, we haven't comments for this post</h2>
    {% endif %}

    </div>
</div>
<script>
$(document).ready(function(){
    $('#favorite_add_remove').on('click', function (e) {
        e.preventDefault();
        var post_id = $('#favorite_add_remove').attr('data-id');
        var url_ajax = "{% url 'post:add_to_favorite' id=123 %}".replace('/123/', '/'+String(post_id)+'/');
        data = {
            post_id: post_id,
        };
        $.ajax({
            type: "GET",
            url: url_ajax,
            dataType: "json",
            data: data,
            success: function (data) {
                if (data['key'] === 0){
                    document.getElementById("favorite_add_remove").className = 'btn btn-warning';
                    document.getElementById("favorite_add_remove").textContent="Remove from favorite";

                } else {
                    document.getElementById("favorite_add_remove").className = 'btn btn-success';
                    document.getElementById("favorite_add_remove").textContent="Add to favorite";

                }
            }
        })

    })
})
</script>
<script>
    $(document).ready(function(){
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        $('#add_comment').on('click', function (e) {
            e.preventDefault();
            var post_id = $('#post').attr('data-id');
            var comment = $('#id_content').val()
            data = {
                post_id: post_id,
                comment: comment,
                csrfmiddlewaretoken: csrftoken
            }
            $.ajax({
                type: "POST",
                url: "{% url 'post:add_comment' %}",
                dataType: "json",
                data: data,
                success: function (data) {
                    data = data[0];
                    var auth_id = data['author_id'];
                    var url_mask = "{% url 'accounts:account' id=123 %}".replace(/123/, auth_id);
                    $('.new_comment').prepend(
                        "<div class=\"row\" style=\"margin-top: 24px;\">\n" +
                        "    <div class=\"col-md-12\">\n" +
                        "      <div class=\"mdb-feed\">\n" +
                        "        <div class=\"news\">\n" +
                        "          <div class=\"label\">\n" +
                        "            <img src=\""+data['author_image']+"\" class=\"rounded-circle z-depth-1-half\">\n" +
                        "          </div>\n" +
                        "          <div class=\"excerpt\">\n" +
                        "            <div class=\"brief\">\n" +
                        "              <a class=\"name\" href=\""+url_mask+"\">"+data['author']+"</a>\n" +
                        "            </div>\n" +
                        "            <div class=\"added-text\">"+data['comment']+"</div>\n" +
                        "          </div>\n" +
                        "        </div>\n" +
                        "      </div>\n" +
                        "    </div>\n" +
                        "  </div>"
                        )
                    $('#id_content').val('')
                }
            })

        })
    });
</script>
<script>
    $(document).ready(function(){
        $('.like_class').on('click', function (e) {
            e.preventDefault();
            var post_id = $('.like_class').attr('data-id');
            data = {
                post_id: post_id,
            };

            $.ajax({
                type: "GET",
                url: "{% url "post:like_page" id=post.id%}",
                dataType: "json",
                data: data,
                success: function (data) {
                    var like_count = parseInt($('#total_likes').attr('data-id'));
                    key = data['key'];
                    if (key === 0) {
                        $('.like_class').html('Like');
                        var c = like_count - 1;
                        $('#total_likes').html('Total likes: '+c);
                        $('#total_likes').attr('data-id', c);
                        document.getElementById("like_dislike").className = "btn btn-primary like_class";
                    } else {
                        $('.like_class').html('Remove like');
                        var c = like_count + 1;
                        $('#total_likes').html('Total likes: '+c);
                        $('#total_likes').attr('data-id', c);
                        document.getElementById("like_dislike").className = "btn btn-warning like_class";
                    }
                }
            });

        })
    });
</script>
<script>
    $(document).ready(function(){
        $('.basket_new').on('click', function (e) {
            e.preventDefault();
            var post_id = $('.basket_new').attr('data-id');
            data = {
                post_id: post_id,
            };
            $.ajax({
                type: "GET",
                url: "{% url "post:add_to_basket" id=post.id %}",
                dataType: "json",
                data: data,
                success: function (data) {
                    if (data['ok'] == 'Added'){
                        document.getElementById("Basketid").className = "btn btn-warning basket_new";
                        document.getElementById("Basketid").innerHTML  = "REMOVE FROM BASKET";
                        $(this).attr('data-action', 'Remove');
                    }
                    if (data['ok'] == 'Removed'){
                        document.getElementById("Basketid").className = "btn btn-success basket_new";
                        document.getElementById("Basketid").innerHTML  = "ADD TO BASKET";
                        $('.basket_new').attr('data-action', 'Add');
                    }
                }
            });
        })
    });
</script>

<br>
{% endblock %}

templates/home/home_page.html
{% extends "home/base.html" %}


{% block content %}
    <div class="user_div">

    <br><br>
    <div class="container-fluid">

        <div class="row">
            <div class="col-1"></div>
            <div class="col-8">

            <h2>Choose article's rate</h2>


            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url "post:high_middle_low_rate" slug='high_rate' %}" class="btn blue-gradient btn-rounded">High</a>
                <a href="{% url "post:high_middle_low_rate" slug='middle_rate' %}" class="btn aqua-gradient btn-rounded">Middle</a>
                <a href="{% url "post:high_middle_low_rate" slug='low_rate' %}" class="btn blue-gradient btn-rounded">Low</a>
            </div>
            <br>
            <hr>
                <br>
            {% if request.user.is_staff or request.user.is_superuser %}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a class="btn btn-primary" href="{% url "post:category_view" %}">Category</a>
                    <br>
                    <br>
                    <a href="{% url "post:create_post" %}" class="btn btn-success">Add new post</a>
                    <br>
                </div>
                <br><br>
            {% else %}
                <a class="btn btn-primary" href="{% url "post:category_view" %}">Category</a>
            {% endif %}

            {% if posts %}
            <div class="row">
                {% for post in posts %}
                    {% if forloop.counter0|divisibleby:2 %}
                        </div><br><br><div class="row">
                    {% endif %}
                        <div class="home_div col-xs-6 col-lg-3">
                            <div class="card card-cascade width_card">
                              <div class="view view-cascade overlay">
                                  {% if post.image %}
                                      <div class="view zoom">
                                        <img src="{{ post.image.url }}" class="img-fluid " alt="">
                                    </div>
                                      <div class="mask flex-center rgba-black-strong">
                                        <p class="white-text">Author: {{ post.user.username }}</p>
                                    </div>
                                {% endif %}
                              </div>
                              <div class="card-body card-body-cascade text-center">
                                <h4 class="card-title"><strong><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></strong></h4>
                                <p class="card-text"> User: <a href="{{ post.get_user_url }}">{{ post.user.username }}</a> | Article rate: {{ post.rate }} Category: <a href="{% url "post:category_detail_view" slug=post.category.name %}">{{ post.category.name }}</a></p>
                                <a href="{{ post.get_absolute_url }}" class="btn peach-gradient btn-lg ">Read more</a>
                              </div>
                            </div>
                        </div>
                {% endfor %}
             {% endif %}

            </div>
        </div>
        <div class="row">
            <div class="col-xs-1"></div>
            <div class="home_div_bot col-xs-1">
                <h2>Popular news:</h2>

                <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
                        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
                    </ol>

                    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width: 220px;">
                        <ol class="carousel-indicators">
                          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                          <li data-target="#myCarousel" data-slide-to="1"></li>
                          <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            {% for post in popular_posts %}
                                {% if forloop.first %}
                                  <div class="carousel-item active">
                                    <img class="first-slide" src="{{ post.image.url }}" style="width: 100%; height: 250px;" alt="First slide">
                                    <div class="container">
                                      <div class="carousel-caption text-left">
                                      </div>
                                    </div>
                                  </div>
                                {% else %}
                                  <div class="carousel-item">
                                    <img class="second-slide" src="{{ post.image.url }}" style="width: 100%; height: 250px;" alt="Second slide">
                                    <div class="container">
                                      <div class="carousel-caption">
                                      </div>
                                    </div>
                                  </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div>
                </div>
            </div>
        </div>
    </div>
        </div>

        <hr>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-1"></div>
        <div class="home_div_bot col-xs-5">
            <h2>Our best posts: </h2>
            <br>
            <div class="row">
                <div class="col-xs-12">
                    <p id="post-image"><img src="{{ posts.last.image.url }}" alt="" class="ImgAddAjax rounded"></p>
                </div>
                <br>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    {% for popular_post in popular_posts %}
                            <h4 class="home_h4"><a href="{{ popular_post.get_absolute_url }}" class="post" data-id="{{ popular_post.id }}">{{ popular_post.title }}</a></h4>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
    <script>
        $(document).ready(function(){
            $('.post').on('mouseenter', function () {
                var post_id = $(this).attr('data-id');

                data = {
                    post_id: post_id
                };
                $.ajax({
                    type: "GET",
                    url: '{% url "post:dynamic_image" %}',
                    data: data,
                    dataType: "json",
                    success: function (data) {
                        $('#post-image').html('<img class="ImgAjax rounded" src="http://127.0.0.1:8000'+data.post_image+'">')
                    }
                })

            })
        });
    </script>

{% endblock %}