accounts/api/urls.py
from django.urls import include, path
from .views import Register

urlpatterns = [
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('custom_registration/', Register.as_view()),
    path('', include('django.contrib.auth.urls')),
]

accounts/urls.py
from django.urls import path, re_path

from .views import (
    account_home,
    account_change_profile,
    change_password,
    remove_from_basket
)


urlpatterns = [
    path('edit/', account_change_profile, name='account_change_profile'),
    path('change_password/', change_password, name='change_password'),
    re_path('^(?P<id>\d+)/$', account_home, name='account'),
    re_path('^(?P<id_element>\d+)/remove$', remove_from_basket, name='remove_from_basket'),
]

post/urls.py
from django.urls import path, re_path
from .views import (
    home_page,
    detail_page,
    edit_page,
    delete_page,
    create_post,
    like_page,
    high_middle_low_rate,
    dynamic_image,
    category_view,
    category_detail_view,
    add_comment,
    display_posts_by_category,
    add_to_favorite,
    search,
    add_to_basket,
    )

app_name = 'post-api'

urlpatterns = [
    path('', home_page, name='home_page'),
    path('add_comment/', add_comment, name='add_comment'),
    path('search/', search, name='search'),
    path('display_posts_by_category', display_posts_by_category, name='display_posts_by_category'),
    re_path('^rate/(?P<slug>[-\w]+)/$', high_middle_low_rate, name='high_middle_low_rate'),
    path('category/', category_view, name='category_view'),
    re_path('^category/(?P<slug>[-\w]+)/$', category_detail_view, name='category_detail_view'),
    path('create/', create_post, name='create_post'),
    path('show_post_image/', dynamic_image, name='dynamic_image'),
    re_path('^(?P<id>\d+)/$', detail_page, name='detail_page'),
    re_path('^(?P<id>\d+)/add_to_basket$', add_to_basket, name='add_to_basket'),
    re_path('^(?P<id>\d+)/add_to_favorite/$', add_to_favorite, name='add_to_favorite'),
    re_path('^(?P<id>\d+)/like$', like_page, name='like_page'),
    re_path('^(?P<id>\d+)/edit/$', edit_page, name='edit_page'),
    re_path('^(?P<id>\d+)/delete/$', delete_page, name='delete_page'),
]

project2big/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

from accounts.views import login_view, logout_view, register_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('start.urls', 'start'), namespace='start')),
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('register/', register_view, name='register_view'),
    path('posts/', include(('post.urls', 'post'), namespace='post')),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('chat/', include(('chat_message.urls', 'chat_message'), namespace='chat_message')),
    path('api-auth/', include('rest_framework.urls')),

    path('api/posts/', include('post.post_api.urls')),
    path('api/account/', include('accounts.api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

start/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

accounts/api/models.py
from django.db import models

# Create your models here.

accounts/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media',
                              null=True,
                              blank=True,
                              default='media/social.jpg'
                              )
    # 'effects.Effect', through = 'ItemEffect', blank = True
    favorite_posts = models.ManyToManyField('post.Posts', blank=True)

    class Meta:
        verbose_name = 'UserProfile'
        verbose_name_plural = 'UserProfiles'

    def get_user_url(self):
        return reverse("accounts:account", kwargs={"id": self.user_id})

    def __str__(self):
        return self.user.username

accounts/forms.py
from django.contrib.auth import (
    authenticate,
    get_user_model,
)
from django import forms


from .models import UserProfile


User = get_user_model()


class UploadImage(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'image'
        ]


class ChangePassword(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput, label="Confirm password")

    class Meta:
        model = User
        fields = [
            'password',
        ]

    def clean(self, *args, **kwargs):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError("Password don't math!")
        if len(password) < 8:
            raise forms.ValidationError("Password less then 8 letters")
        return super(ChangePassword, self).clean(*args, **kwargs)


class ChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
        ]


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = User.objects.filter(username=username).exists()
            if not user:
                raise forms.ValidationError("This user does not exist")
            user = User.objects.get(username=username)
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect passsword")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(LoginForm, self).clean(*args, **kwargs)


class RegisterForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField(label='Email address')
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm password')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password2'
        ]

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        user_username = User.objects.filter(username=username)
        if user_username.exists():
            raise forms.ValidationError("A user with that username already exists.")
        if password != password2:
            raise forms.ValidationError("Password don't match")
        if len(password) < 8:
            raise forms.ValidationError("Password must me bigger then 8 characters")
        if password in [email, username]:
            raise forms.ValidationError("Password equal to email or username")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already exist")
        return super(RegisterForm, self).clean(*args, **kwargs)

accounts/api/views.py
from django.contrib.auth.models import User

from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import UserCreateSerializer


class Register(APIView):

    def post(self, request, *args, **kwargs):
        serializer = UserCreateSerializer(data=request.data)

        if serializer.is_valid():
            username = serializer.data.get('username')
            email = serializer.data.get('email')
            password = serializer.data.get('password')

            user = User.objects.create_user(username, email, password)
            token = Token.objects.create(user=user)

            context = {
                'key': token.key
            }

            return Response(context)

        return Response(data=serializer.errors)

accounts/views.py
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    )
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.urls import reverse


from django.contrib.auth.decorators import login_required
from baskets.models import Basket
from .models import UserProfile
from post.models import Posts
from .forms import (
    LoginForm,
    RegisterForm,
    ChangeForm,
    ChangePassword,
    UploadImage
    )


@login_required
def remove_from_basket(request, id_element):
    post = Posts.objects.get(id=id_element)
    basket = Basket.objects.get(user=request.user).product.remove(post)
    return JsonResponse({'ok': 'ok'})


def change_password(request):
    form = ChangePassword()

    if request.POST:
        form = ChangePassword(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get("password")
            request.user.set_password(password)
            request.user.save()
            user = authenticate(username=request.user.username, password=request.user.password)
            login(request, user)

            redirect_to_profile = reverse("accounts:account", kwargs={"id": request.user.id})
            return HttpResponseRedirect(redirect_to_profile)

    context = {
        'form': form
    }
    return render(request, "accounts/change_password.html", context)


def account_change_profile(request):
    form = ChangeForm()

    if request.POST:
        form = ChangeForm(request.POST)
        if form.is_valid():
            request.user.first_name = form.cleaned_data.get('first_name')
            request.user.last_name = form.cleaned_data.get('last_name')
            request.user.save()

            redirect_to_profile = reverse("accounts:account", kwargs={"id": request.user.id})
            return HttpResponseRedirect(redirect_to_profile)

    context = {
        'form': form
    }
    return render(request, "accounts/change_profile.html", context)


def account_home(request, id):
    user = get_object_or_404(User, id=id)

    baskets = 'False'
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        if basket.exists():
            baskets = basket[0].product.prefetch_related().all()

    userprofile = get_object_or_404(UserProfile, user=user)
    form = UploadImage()

    if request.POST:
        form = UploadImage(request.POST, request.FILES or None)

        if form.is_valid():
            userprofile.image = form.cleaned_data.get("image")
            userprofile.save()
            return HttpResponseRedirect(userprofile.get_user_url())

    favorite_posts = None
    if request.user == user:
        favorite_posts = userprofile.favorite_posts.prefetch_related().all()

    context = {
        'user': user,
        'form': form,
        'userprofile': userprofile,
        'favorite_posts': favorite_posts,
        'baskets': baskets,
        'baskets_len': len(baskets)
    }
    return render(request, "accounts/user_account.html", context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse("post:home_page"))

    form = LoginForm()

    title = "Login"
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse("post:home_page"))
            return redirect(reverse("login_view"))

    context = {
        "form": form,
        "title": title
    }

    return render(request, "accounts/login_register_forms.html", context)


def register_view(request):
    if request.user.is_authenticated:
        return redirect(reverse("post:home_page"))

    title = "Registration"
    form = RegisterForm()

    if request.POST:
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            new_user = authenticate(username=user.username, password=password)
            UserProfile.objects.create(user=new_user)
            login(request, new_user)
            return redirect(reverse("post:home_page"))

    context = {
        "form": form,
        'title': title
    }

    return render(request, "accounts/login_register_forms.html", context)


def logout_view(request):
    if request.POST:
        logout(request)
        return redirect("/")

templates/accounts/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en" class="full-height">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/compiled.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static "css/custom_style.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    {% block head %}
    {% endblock %}

</head>
<body class="user_div">

<nav class="navbar navbar-expand-lg navbar-dark primary-color fixed-top scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url "start:home" %}">
        <strong>Python for everyone</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "post:home_page" %}">Posts
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url "post:search" %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
          <ul class="navbar-nav nav-flex-icons">
              {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">You: {{ request.user.username }}</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url "accounts:account" id=request.user.id %}">My account</a>
                        <a class="dropdown-item" href="{% url "accounts:account_change_profile" %}">Edit account</a>
                        <a class="dropdown-item" href="{% url "accounts:change_password" %}">Change password</a>
                        <form action="{% url "logout_view" %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="dropdown-item" value="Logout">
                        </form>
                    </div>
                  </li>
              {% else %}
                  <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url "login_view" %}">Login</a>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url "register_view" %}">Register</a>
                      </li>
                    </ul>
              {% endif %}
          </ul>

      </div>
    </div>
  </nav>

<div class="user_div">
    <br><br>
    {% block content %}

    {% endblock %}
    <br>
</div>


    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/compiled.min.js" %}"></script>
</body>
</html>

templates/accounts/change_password.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <br><br>
    <div class="container">
        <div class="col-xs-8 col-xs-offset-2">
            <h2>Change password:</h2>
            <form action="." method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success">
            </form>
        </div>
    </div>

{% endblock %}

templates/accounts/change_profile.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <br><br>
    <div class="container">
        <div class="col-xs-8 col-xs-offset-2">
            <h2>Change profile info:</h2>
            <form action="." method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success">
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/login_register_forms.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <br><br>
<div class="container">
    <h2>{{ title }} page</h2>
    <form method='POST' action='.'>
        {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class='btn btn-success' id="alert-target">
    </form>
</div>

{% endblock content%}

templates/accounts/user_account.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<br><br>
<div class="user_div">
    <div class="container">
        <div class="col-xs-8 col-xs-offset-2">
            {% if user.id == request.user.id %}
            <h2>Welcome to your profile!</h2>
                <hr>
                {% if userprofile.favorite_posts.all %}
                    <h2>Your favourite posts:</h2>
                {% else %}
                    <h2>Your haven't favorite posts yet</h2>
                {% endif %}
                <div class="row">
                {% for favorite_post in userprofile.favorite_posts.all  %}
                    {% if forloop.counter0|divisibleby:4 %}
                        </div><br><div class="row">
                    {% endif %}

                    <div id="{{ favorite_post.id }}" class="card" style="margin-left: 15px; margin-bottom: 15px; height: 350px; width: 265px;">
                      <div class="view overlay">
                        <img class="card-img-top" src="{{ favorite_post.image.url }}" alt="Card image cap">
                        <a>
                          <div class="mask rgba-white-slight"></div>
                        </a>
                      </div>
                      <div class="card-body">
                        <a class="activator waves-effect waves-light mr-4"><i class="fa fa-share-alt"></i></a>
                        <h4 class="card-title">{{ favorite_post.title }}</h4>
                        <hr>
                        <p class="card-text">{{ favorite_post.content|truncatechars:20 }}</p>
                        <a href="{{ favorite_post.get_absolute_url }}" class="black-text d-flex justify-content-end"><h5>Read more<i class="fa fa-angle-double-right"></i></h5></a>
                        <a href="" id="{{ favorite_post.id }}" data-id="{{ favorite_post.id}}" class="favorite_add_remove red-text d-flex justify-content-end"><h6>Remove</h6></a>
                      </div>
                    </div>
                {% endfor %}
                </div>
                <hr>

                {% if baskets != 'False' %}
                        <div class="container" id='buy_count' data-len="{{ baskets_len }}">
                            <div class="row">
                                    <div class="body">
                                        <div class="table">
                                            <table class="table product-table">
                                                <thead class="mdb-color lighten-5">
                                                    <tr>
                                                        <th></th>
                                                        <th class="font-weight-bold">
                                                            <strong>Title</strong>
                                                        </th>
                                                        <th class="font-weight-bold">
                                                            <strong>Category</strong>
                                                        </th>
                                                        <th></th>
                                                        <th class="font-weight-bold">
                                                            <strong>QTY</strong>
                                                        </th>
                                                        <th class="font-weight-bold">
                                                            <strong>Price</strong>
                                                        </th>
                                                        <th class="font-weight-bold">
                                                            <strong>Delete</strong>
                                                        </th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                {% for product in  baskets %}
                                                    <tr id="{{ product.id }}list">
                                                        <th scope="row">
                                                            <img src="{{ product.image.url }}" alt="" class="img-fluid z-depth-0">
                                                        </th>
                                                        <td>
                                                            <h5 class="mt-3">
                                                                <strong>{{ product.title|truncatechars:20 }}</strong>
                                                            </h5>
                                                        </td>
                                                        <td>{{ product.category.name }}</td>
                                                        <td></td>
                                                        <td>
                                                            <input oninput="return ChangeInput(this);"  type="number" value="1" data-pred-val="1" aria-label="Search" class="form-control new-input" data-price="{{ product.views }}" id='count_element{{ forloop.counter }}' style="width: 100px">
                                                        </td>
                                                        <td class="font-weight-bold">
                                                            <strong id="id_tr{{ forloop.counter }}">{{ product.views }}</strong>
                                                        </td>
                                                        <td>
                                                            <a href="{% url "accounts:remove_from_basket" id_element=product.id %}" data-id="{{ product.id }}" class="btn btn-sm btn-primary remove_from_list" data-toggle="tooltip" data-placement="top" title="Remove item">X
                                                            </a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}

                                                    <tr>
                                                        <td colspan="3"></td>
                                                        <td>
                                                            <h4 class="mt-2">
                                                                <strong>Total</strong>
                                                            </h4>
                                                        </td>
                                                        <td class="text-right">
                                                            <h4 class="mt-2">
                                                                <strong class="price-buy">$2600</strong>
                                                            </h4>
                                                        </td>
                                                        <td colspan="3" class="text-right">
                                                            <button type="button" class="btn btn-primary btn-rounded">Complete purchase
                                                                <i class="fa fa-angle-right right"></i>
                                                            </button>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                            </div>
                            </div>
                        </div>
            {% endif %}

                <hr>
                <br>
            {% else %}
                <h2>Welcome to {{ user.username }}'s profile!</h2>
            {% endif %}
            <br>
            <div class="user_account rounded">
                <h3>Username: {{ user.username }}</h3>
                <h3>Email: {{ user.email }}</h3>

                {% if userprofile.image %}
                    <h3>Profile image: </h3>
                    <img class="profileimg" src="{{ userprofile.image.url }}" alt="">
                {% else %}
                    <h3>Profile image: -</h3>
                {% endif %}
                <br>
                <br>
                {% if user.first_name %}
                    <h3>First name: {{ user.first_name }}</h3>
                {% else %}
                    <h3>First name: -</h3>
                {% endif %}
                {% if user.last_name %}
                    <h3>Last name: {{ user.last_name }}</h3>
                {% else %}
                    <h3>Last name: -</h3>
                {% endif %}<h4>Registration date: {{ user.date_joined }}</h4>
            </div>
            <br>
            {% if request.user == user %}
                <h2>Upload profile image:</h2>
                <form action="." method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-success" value="Send">
                </form>
                <hr>

                <a href="{% url "logout_view" %}" class="btn btn-warning btn-lg">Logout</a>
            {% endif %}
                <a href="{% url "post:home_page" %}" class="btn btn-primary btn-lg">Back to posts</a>

        </div>
    </div>
    <br><br><br>
</div>

<script>
    window.onload = function() {
        var count = $('#buy_count').attr('data-len');
        var myArray = [];
        var sum = 0;
        for (var i=1; i<=count; i++){
            var element = $('#id_tr'+String(i)).text();
            var price = $('#count_element'+String(i)).val();
            sum = sum + parseInt(element) * parseInt(price);
        }
        $('.price-buy').text(sum);
    };
</script>
    
<script>
    function ChangeInput(Element) {
        var pred = $(Element).attr('data-pred-val')

        $(Element).attr('data-pred-val', Element.value)
        var value_input = Element.value
        var sum = 0
        if (pred<value_input){
            sum = parseInt($('.price-buy').text()) + parseInt($(Element).attr('data-price') * (value_input-pred));
        } else {
            sum = parseInt($('.price-buy').text()) - (parseInt($(Element).attr('data-price')) * (pred-value_input));
        }
        $('.price-buy').text(sum);
    }
</script>

<script>
$(document).ready(function(){
    $('.favorite_add_remove').on('click', function (e) {
        e.preventDefault();
        var post_id = $(this).attr('data-id');
        console.log(post_id)
        var url_ajax = "{% url 'post:add_to_favorite' id=123 %}".replace('/123/', '/'+String(post_id)+'/');
        data = {
            post_id: post_id,
        };
        console.log(url_ajax);
        $.ajax({
            type: "GET",
            url: url_ajax,
            dataType: "json",
            data: data,
            success: function (data) {
                document.getElementById(post_id).remove();
            }
        })

    })
})
</script>

<script>
    $(document).ready(function(){
        $('.remove_from_list').on('click', function (e) {
            e.preventDefault();
            var post_id = $(this).attr('data-id');
            console.log(post_id)
            var url_ajax = "{% url 'accounts:remove_from_basket' id_element=123 %}".replace('/123/', '/'+String(post_id)+'/');
            data = {
                post_id: post_id,
            };
            console.log(url_ajax);
            $.ajax({
                type: "GET",
                url: url_ajax,
                dataType: "json",
                data: data,
                success: function (data) {
                    document.getElementById(post_id+'list').remove();
                }
            })

        })
    })
</script>

{% endblock %}