accounts/urls.py
from django.urls import path, re_path

from .views import (
    account_home,
    account_change_profile,
    change_password,
    remove_from_basket
)


urlpatterns = [
    path('edit/', account_change_profile, name='account_change_profile'),
    path('change_password/', change_password, name='change_password'),
    re_path('^(?P<id>\d+)/$', account_home, name='account'),
    re_path('^(?P<id_element>\d+)/remove$', remove_from_basket, name='remove_from_basket'),
]

post/urls.py
from django.urls import path, re_path
from .views import (
    home_page,
    detail_page,
    edit_page,
    delete_page,
    create_post,
    like_page,
    high_middle_low_rate,
    dynamic_image,
    category_view,
    category_detail_view,
    add_comment,
    display_posts_by_category,
    add_to_favorite,
    search,
    add_to_basket,
    )

app_name = 'post-api'

urlpatterns = [
    path('', home_page, name='home_page'),
    path('add_comment/', add_comment, name='add_comment'),
    path('search/', search, name='search'),
    path('display_posts_by_category', display_posts_by_category, name='display_posts_by_category'),
    re_path('^rate/(?P<slug>[-\w]+)/$', high_middle_low_rate, name='high_middle_low_rate'),
    path('category/', category_view, name='category_view'),
    re_path('^category/(?P<slug>[-\w]+)/$', category_detail_view, name='category_detail_view'),
    path('create/', create_post, name='create_post'),
    path('show_post_image/', dynamic_image, name='dynamic_image'),
    re_path('^(?P<id>\d+)/$', detail_page, name='detail_page'),
    re_path('^(?P<id>\d+)/add_to_basket$', add_to_basket, name='add_to_basket'),
    re_path('^(?P<id>\d+)/add_to_favorite/$', add_to_favorite, name='add_to_favorite'),
    re_path('^(?P<id>\d+)/like$', like_page, name='like_page'),
    re_path('^(?P<id>\d+)/edit/$', edit_page, name='edit_page'),
    re_path('^(?P<id>\d+)/delete/$', delete_page, name='delete_page'),
]

project2big/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

from accounts.views import login_view, logout_view, register_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('start.urls', 'start'), namespace='start')),
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('register/', register_view, name='register_view'),
    path('posts/', include(('post.urls', 'post'), namespace='post')),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('chat/', include(('chat_message.urls', 'chat_message'), namespace='chat_message')),
    path('api-auth/', include('rest_framework.urls')),

    path('api/posts/', include('post.post_api.urls')),
    path('api/account/', include('accounts.api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

start/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

templates/chat/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en" class="full-height">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/compiled.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static "css/custom_style.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    {% block head %}
    {% endblock %}

</head>
<body class="user_div">

<nav class="navbar navbar-expand-lg navbar-dark primary-color fixed-top scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url "start:home" %}">
        <strong>Python for everyone</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "post:home_page" %}">Posts
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url "post:search" %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
          <ul class="navbar-nav nav-flex-icons">
              {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">You: {{ request.user.username }}</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url "accounts:account" id=request.user.id %}">My account</a>
                        <a class="dropdown-item" href="{% url "accounts:account_change_profile" %}">Edit account</a>
                        <a class="dropdown-item" href="{% url "accounts:change_password" %}">Change password</a>
                        <form action="{% url "logout_view" %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="dropdown-item" value="Logout">
                        </form>
                    </div>
                  </li>
              {% else %}
                  <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url "login_view" %}">Login</a>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url "register_view" %}">Register</a>
                      </li>
                    </ul>
              {% endif %}
          </ul>

      </div>
    </div>
  </nav>

<div class="user_div">
    <br><br>
    {% block content %}

    {% endblock %}
    <br>
</div>


    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/compiled.min.js" %}"></script>
</body>
</html>

templates/chat/chat_home.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/chat_css.css" %}">
    <script type="text/javascript" src="{% static "js/chat_js.js" %}"></script>
{% endblock %}


{% block content %}
<div class="user_div">
    <div class="card rare-wind-gradient chat-room">

    <br>
    <div class="card-body">
        <div class="row px-lg-2 px-2">
            <div class="col-2"></div>
            <div class="col-8">
                <h2 class="alert alert-light text-center">Global chat:</h2>
                <hr>
                <div class="chat-message">
                    <ul class="list-unstyled chat-1 scrollbar-light-blue">
                        {% for message in messages %}
                            <li class="d-flex justify-content-between mb-4 mr-4">
                                {% if message.author == request.user %}
                                    <a href="{{ message.get_user_url }}"><img src="{{ message.author_profile.image.url }}" alt="avatar" class="avatar rounded-circle mr-2 ml-lg-3 ml-0 z-depth-1"></a>
                                {% endif %}
                                <div class="chat_div chat-body white p-3 ml-2 z-depth-1">
                                    <div class="header">
                                        <a href="{{ message.get_user_url }}">
                                            <strong class="primary-font">{{ message.author.username }}</strong>
                                        </a>
                                    </div>
                                    <hr class="w-100">
                                    <p class="chat_p mb-0">
                                        {{ message.content }}
                                    </p>
                                </div>
                                {% if message.author != request.user %}
                                    <img src="{{ message.author_profile.image.url }}" alt="avatar" class="avatar rounded-circle mr-2 ml-lg-3 ml-0 z-depth-1">
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                    {% if request.user.is_authenticated %}
                        <form action="."  method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input class="btn btn-success" value="Send" type="submit">
                        </form>
                    {% else %}
                        <hr>
                        <a href="{% url "login_view" %}" class="btn btn-success">Login</a> <br>
                        <a href="{% url "register_view" %}" class="btn btn-success">Registration</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}